language: php

addons:
  code_climate:
    repo_token:

php:
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/test-reporter
